# [LAB-02] NumPy

## 1. NumPy 시작하기

### #01 준비 작업

1. 라이브러리 참조하기

In [3]:
# numpy 라이브러리를 np라는 이름으로 사용
import numpy as np

### #02 배열 생성하기

1. 리스트를 통한 1차원(=1행으로 구성) 배열 만들기

In [4]:
# list를 파라미터로 전달해 ndarray 객체 생성
arr = np.array([1, 3, 5, 7, 9])
print(type(arr))
arr

<class 'numpy.ndarray'>


array([1, 3, 5, 7, 9])

### #03 리스트와 동일한 특성

1. 배열의 크기

In [5]:
arr = np.array([10, 30, 50, 70, 90])
size = len(arr)
print("배열의 원소는 %d개 입니다." % size)

배열의 원소는 5개 입니다.


2. 인덱싱과 슬라이싱

In [6]:
mydata = np.array([5, 10, 15, 20, 25])

# 인덱싱을 사용한 원소의 접근
print(mydata[0])
print(mydata[1])
print(mydata[3])

# 슬라이싱을 사용한 구간 추출
print(mydata[1:4])
print(mydata[-4:-1])

5
10
20
[10 15 20]
[10 15 20]


3. 반복문을 통한 활용

In [7]:
mydata = np.array([100, 110, 120, 130, 140])

for i, v in enumerate(mydata):
    print("%d번째 원소 >> %d" % (i, v))

0번째 원소 >> 100
1번째 원소 >> 110
2번째 원소 >> 120
3번째 원소 >> 130
4번째 원소 >> 140


### #04 ndarray의 특성

1. list 타입 원소의 종류

In [8]:
mylist = [100, 3.14, True]
mylist

[100, 3.14, True]

2. ndarray 타입 원소의 종류

In [9]:
myarr = np.array(mylist)
myarr

array([100.  ,   3.14,   1.  ])

### #05 ndarray의 데이터 타입

1. dtype 파라미터를 사용한 강제 타입 지정

In [10]:
mylist1 = [100.12, 3.14, 1.5]
myarr1 = np.array(mylist1, dtype='int')
myarr1

array([100,   3,   1])

2. 문자열이 포함된 경우의 형변환

In [11]:
mylist2 = [1.2, 3, True, '4']
myarr2 = np.array(mylist2)
myarr2

array(['1.2', '3', 'True', '4'], dtype='<U32')

### #06 list 타입으로 역변환

1. ndarray와 list는 서로 호환 가능

In [12]:
mylist3 = [10, 20, 30, 40, 50]
myarr3 = np.array(mylist3)
print(type(myarr3), myarr3)

mylist3_1 = list(myarr3)
print(type(mylist3_1), mylist3_1)

<class 'numpy.ndarray'> [10 20 30 40 50]
<class 'list'> [np.int64(10), np.int64(20), np.int64(30), np.int64(40), np.int64(50)]


### #07 ndarray 연산

1. 연산자 위치 -> 위치가 동일한 원소끼리 연산

In [14]:
arr1 = np.array([10, 15, 20, 25, 30])
arr2 = np.array([2, 3, 4, 5, 6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [16]:
a = arr1 + arr2
a

array([12, 18, 24, 30, 36])

In [17]:
b = arr1 - arr2
b

array([ 8, 12, 16, 20, 24])

In [18]:
c = arr1 * arr2
c

array([ 20,  45,  80, 125, 180])

In [19]:
d = arr1 / arr2
d

array([5., 5., 5., 5., 5.])

2. NumPy의 함수를 사용한 연산 -> 연산자를 사용한 경우와 동일 결과

In [20]:
arr1 = np.array([10, 15, 20, 25, 30])
arr2 = np.array([2, 3, 4, 5, 6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [21]:
a = np.add(arr1, arr2)
a

array([12, 18, 24, 30, 36])

In [22]:
a = np.subtract(arr1, arr2)
a

array([ 8, 12, 16, 20, 24])

In [23]:
a = np.multiply(arr1, arr2)
a

array([ 20,  45,  80, 125, 180])

In [24]:
a = np.divide(arr1, arr2)
a

array([5., 5., 5., 5., 5.])

3. 논리 연산(1) - 조건에 맞는 위치의 원소 추출

In [25]:
# 철수의 1~4학년까지의 평균 점수
grade = np.array([82, 77, 91, 88])
grade

array([82, 77, 91, 88])

In [26]:
# -> 추출하고자 하는 원본과 같은 사이즈의 배열을 생성
# -> 추출할 값은 True, 그렇지 않으면 False
bool_array = np.array([True, False, True, False])
bool_array

array([ True, False,  True, False])

In [28]:
# -> 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
result1

array([82, 91])

4. 논리 연산(2) - 조건식에 맞는 원소 추출

In [30]:
# 80점 이상은 원소만 추출
# -> 조건을 명시하기 위해 배열의 이름이 조건식에 명시된다
mypoint = np.array([82, 77, 91, 88])
ge80 = mypoint[mypoint >= 80]
ge80

array([82, 91, 88])

In [32]:
ge80le90 = mypoint[np.logical_and(mypoint >= 80, mypoint <= 90)]
ge80le90

array([82, 88])

In [33]:
gt_or_lt = mypoint[np.logical_or(mypoint < 80, mypoint > 90)]
gt_or_lt

array([77, 91])

### #08 조건 분기

1. if~else 효과

In [34]:
exam = np.array([60, 83, 75, 92, 86])

# 첫 번째 파라미터로 주어진 조건이 참일 경우 '합격',
# 그렇지 않을 경우 '불합격'
result = np.where(exam >= 80, '합격', '불합격')
result

array(['불합격', '합격', '불합격', '합격', '합격'], dtype='<U3')

2. 다중 조건 분기

In [35]:
exam = np.array([60, 85, 51, 79, 94, 88])

# 학점을 부여하기 위한 점수의 구간을 설정하는 조건들을 리스트로 설정
conditions = [(exam >= 90),     # if
              (exam >= 80),     # elif
              (exam >= 70)      # elif
]

# 조건에 따라 부여될 학점
value = ['A', 'B', 'C']

# 조건과 조건을 판단하기 위한 값을 저장함
# default는 조건에 맞는 값이 아닌 경우 사용됨 (생략 가능)
result = np.select(conditions, value, default='F')
result

array(['F', 'B', 'F', 'C', 'A', 'B'], dtype='<U1')

## 연습문제

□ 다음 조건을 모두 만족하는 파이썬 코드를 작성하시오.

NumPy의 ndarray를 활용하여

1. 정수 10, 20, 30, 40, 50으로 구성된 배열을 생성하고,
2. 배열의 길이(원소 개수)를 출력하며,
3. 배열의 첫 번째 원소와 마지막 두 개 원소를 각각 출력하고,
4. for문과 enumerate()를 이용해 인덱스와 값을 함께 출력하시오.

In [53]:
arr = np.array([10, 20, 30, 40, 50])
size = len(arr)

print(f"배열의 길이: {size}")
print(f"첫 번째 원소: {arr[0]}")
print(f"마지막 두 개 원소: {arr[-2:]}")

for i, v in enumerate(arr):
    print("%d번째 원소 >> %d" % (i, v))


배열의 길이: 5
첫 번째 원소: 10
마지막 두 개 원소: [40 50]
0번째 원소 >> 10
1번째 원소 >> 20
2번째 원소 >> 30
3번째 원소 >> 40
4번째 원소 >> 50
