# [LAB-02] NumPy

## 2. 다양한 ndarray

### #01 준비작업

1. 라이브러리 참조

In [5]:
import numpy as np

### #02 2차원 배열

1. 2차원 리스트의 ndarray 변환

In [6]:
myarray = np.array([
    [98, 72, 80, 64],
    [88, 90, 80, 72],
    [92, 88, 82, 76]
])

print(myarray)

print("차원크기:", myarray.ndim)
print("차원별 원소수:", myarray.shape)
print("원소의 데이터 타입:", myarray.dtype)

[[98 72 80 64]
 [88 90 80 72]
 [92 88 82 76]]
차원크기: 2
차원별 원소수: (3, 4)
원소의 데이터 타입: int64


2. boolean 타입으로 인덱싱

In [8]:
bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [True, False, True, False]
])

# 조건에 맞는 항목만 1차 배열로 추출
# myarray는 이전 실습에서 생성한 2차원 배열
result1 = myarray[bool_array]
result1

array([98, 80, 88, 90, 80, 92, 82])

### #03 비교식에 의한 검색

1. 조건에 맞는 원소를 1차원 배열로 반환한다

In [9]:
result2 = myarray[myarray >= 80]
result2

array([98, 80, 88, 90, 80, 92, 88, 82])

2. AND 검색

In [10]:
result3 = myarray[np.logical_and(myarray >= 80, myarray <= 90)]
result3

array([80, 88, 90, 80, 88, 82])

3. OR 검색

In [11]:
result4 = myarray[np.logical_or(myarray < 80, myarray > 90)]
result4

array([98, 72, 64, 72, 92, 76])

### #04 정형화된 배열 생성

1. 모든 원소가 0인 배열

In [12]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

2. 모든 원소가 1인 배열

In [13]:
np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

3. 모든 원소가 특정 값인 배열

In [14]:
np.full([3, 4], 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

4. 단위 행렬

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### #05 랜덤 배열

1. 0부터 1의 범위에서 균등하게 추출해 N차원 랜덤 배열 생성

In [16]:
np.random.rand(10)

array([0.96646557, 0.58659935, 0.29280262, 0.83669287, 0.84474067,
       0.12882356, 0.72485664, 0.04983657, 0.48150924, 0.31763796])

2. 4행 3열인 2차원 랜덤 배열 생성

In [17]:
np.random.rand(4, 3)

array([[0.90314386, 0.742607  , 0.43787204],
       [0.30389643, 0.65592585, 0.75521647],
       [0.22725428, 0.93641245, 0.70664707],
       [0.15904274, 0.99581137, 0.72185473]])

### #06 주어진 범위 안에서 정수값을 갖는 랜덤 배열

1. 0부터 9 사이의 랜덤값 10개의 원소를 갖는 1차원 배열

In [19]:
np.random.randint(0, 9, 10)

array([2, 5, 2, 0, 0, 7, 4, 3, 1, 5], dtype=int32)

2. 0부터 9 사이의 랜덤값을 갖는 3행 4열의 2차 배열 

In [20]:
np.random.randint(0, 9, (3, 4))

array([[8, 0, 6, 1],
       [1, 1, 8, 0],
       [1, 3, 2, 7]], dtype=int32)

### #07 랜덤 시드

1. 랜덤 시드

난수는 겉보기엔 무작위지만, 실제로는 컴퓨터가 특정 규칙에 따라 만들어내는 가짜 무작위값이다.   
이때 랜덤시드는 그 규칙을 어디서부터 시작할지 정하는 '출발점 값'이다.

2. 랜덤시드를 고정하고 정규 분포를 따르는 랜덤값 생성하기

평균 = 0, 표준편차 = 1, 배열 크기 = 4행 3열

In [22]:
np.random.seed(1234)
np.random.normal(0, 1, (4, 3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

### #08 표준 정규 분포를 따르는 랜덤 배열

1. 원소가 10개인 1차원 배열

In [23]:
np.random.randn(10)

array([ 0.95332413, -2.02125482, -0.33407737,  0.00211836,  0.40545341,
        0.28909194,  1.32115819, -1.54690555, -0.20264632, -0.65596934])

2. 4행 3열의 2차원 배열

In [24]:
np.random.randn(4, 3)

array([[ 0.19342138,  0.55343891,  1.31815155],
       [-0.46930528,  0.67555409, -1.81702723],
       [-0.18310854,  1.05896919, -0.39784023],
       [ 0.33743765,  1.04757857,  1.04593826]])

3. 정규분포를 직접 설정한 1차원 배열

In [25]:
np.random.normal(0, 1, 10)

array([ 0.86371729, -0.12209157,  0.12471295, -0.32279481,  0.84167471,
        2.39096052,  0.07619959, -0.56644593,  0.03614194, -2.0749776 ])

4. 2차원 배열

In [26]:
np.random.normal(0, 1, (4, 3))

array([[ 0.2477922 , -0.89715678, -0.13679483],
       [ 0.01828919,  0.75541398,  0.21526858],
       [ 0.84100879, -1.44581008, -1.40197328],
       [-0.1009182 , -0.54824245, -0.14461951]])

## 연습문제

### 성적 처리 시스템 만들기

당신은 한 학급의 성적 데이터를 NumPy로 분석해야 하는 데이터 분석가입니다.   

학생 6명의 점수 데이터가 다음과 같이 주어집니다.   

score = [72.5, 88.0, 91.5, 67.0, 80.0, 59.5]   

다음 조건에 따라 코드를 작성하세요.   
- 위 점수 리스트를 정수형 ndarray로 변환하세요.
- 점수가 80점 이상인 학생의 점수만 추출하여 출력하세요.
- 모든 학생에게 다음 기준으로 학점을 부여하고 결과를 출력하세요.
- 90점 이상 → ‘A’ / 80점 이상 → ‘B’ / 70점 이상 → ‘C’ / 그 외 → ‘F’

In [ ]:
import numpy as np

score = np.array([72.5, 88.0, 91.5, 67.0, 80.0, 59.5], "int")
ge80 = score[score >= 80]

conditions = [(score >= 90),     # if
              (score >= 80),     # elif
              (score >= 70)      # elif
]

value = ['A', 'B', 'C']
result = np.select(conditions, value, default='F')

print("원본 점수:", score)
print("80점 이상:", ge80)
print("학점 결과:", result)

원본 점수: [72 88 91 67 80 59]
80점 이상: [88 91 80]
학점 결과: ['C' 'B' 'A' 'F' 'B' 'F']


### 2. AI 교육생 점수 데이터 점검하기

당신은 AI 교육기관에서 수강생들의 모의시험 데이터를 검수하는 일을 맡고 있습니다.   
시험 데이터는 3회차 시험 × 4명 학생의 점수로 구성되어야 합니다.   
다음 조건에 맞게 NumPy로 코드를 작성하세요.   

평균이 75, 표준편차가 5인 정규분포를 따르는 랜덤 점수 데이터를 3행 4열 배열로 생성하십시오.   
단, 결과가 재현되도록 랜덤 시드를 100으로 고정해야 함.   
생성된 점수 중 80점 이상인 항목만 추출하시오.   
점수가 저장된 배열의 차원(ndim), 형태(shape), 데이터 타입(dtype) 을 각각 출력하시오.

In [ ]:
import numpy as np

np.random.seed(100)
score = np.random.normal(75, 5, (3, 4))

ge80 = score[score >= 80]

print(score)
print("80점 이상 점수:", ge80)
print("차원:", score.ndim)
print("형태:", score.shape)
print("데이터 타입:", score.dtype)

[[66.25117263 76.71340202 80.76517901 73.73781982]
 [79.90660393 77.57109421 76.10589835 69.64978335]
 [74.05252085 76.27500722 72.70986507 77.17581744]]
80점 이상 점수: [80.76517901]
차원: 2
형태: (3, 4)
데이터 타입: float64
