# [LAB-02] NumPy

## 3. ndarray 형태 변환

### #01 준비작업

1. 라이브러리 참조

In [1]:
import numpy as np

### #02 원소의 데이터 타입 변환(1) - astype() 함수 사용

1. 실습을 위한 원본 배열 구성

In [3]:
# 0~10 전까지 1씩 증가하는 원소를 갖는 배열 생성
arr1 = np.arange(10)
print("원본배열:", arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [0 1 2 3 4 5 6 7 8 9]
원본배열의 데이터 타입: int64


2. 실수(float) 타입으로 변환

In [4]:
arr2 = arr1.astype('float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후의 배열: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
변환된 배열의 데이터 타입: float64


3. 문자열(str) 타입으로 변환

In [5]:
arr3 = arr1.astype('str')
print("형변환 후의 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']
변환된 배열의 데이터 타입: <U21


### #03 원소의 데이터 타입 변환(2) - asarray() 함수 사용

1. 원본 배열 구성

In [6]:
# 0~10 전까지 1씩 증가하는 원소를 갖는 배열 생성
arr1 = np.arange(10, 20)
print("원본배열:", arr1)
print("원본배열의 데이터 타입:", arr1.dtype)

원본배열: [10 11 12 13 14 15 16 17 18 19]
원본배열의 데이터 타입: int64


2. 실수(float) 타입으로 변환

In [9]:
arr2 = np.asarray(arr1, dtype='float')
print("형변환 후의 배열:", arr2)
print("변환된 배열의 데이터 타입:", arr2.dtype)

형변환 후의 배열: [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
변환된 배열의 데이터 타입: float64


3. 문자열(str) 타입으로 변환

In [11]:
arr3 = np.asarray(arr1, dtype='str')
print("형변환 후의 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후의 배열: ['10' '11' '12' '13' '14' '15' '16' '17' '18' '19']
변환된 배열의 데이터 타입: <U21


### #04 reshape() 함수를 사용한 차원 변환

1. 1~20 전까지 1씩 증가하는 값을 갖는 1차원 배열 생성

In [13]:
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

2. 1차원 배열을 4행 5열의 2차원 배열로 변환

In [14]:
x = origin.reshape(4, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

3. 변환할 수 없는 경우

In [15]:
origin.reshape(3, 7)

ValueError: cannot reshape array of size 20 into shape (3,7)

### #05 reshape() 함수를 사용한 차원 축소

1. 원본 배열 구성

In [16]:
origin = np.array([
    [0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14],
    [15, 16, 17, 18, 19],
])

origin

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

2. 1차 배열로 차원 축소하기

In [18]:
y = origin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

3. 원소의 수 계산 후 1차원 배열로 축소하기

In [19]:
rows, cols = origin.shape
rows, cols

(4, 5)

In [20]:
z = origin.reshape(rows * cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

### #06 reshape() 함수에서 -1의 의미

1. reshape(-1, 정수)

1-1. 실습을 위한 원본 배열 생성

In [21]:
origin = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [8, 9, 10, 11]
])

origin

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

1-2. 행의 수에 관계 없이 1열을 갖는 2차원 배열

In [23]:
x = origin.reshape(-1, 1)
x

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

1-3. 행의 수에 관계 없이 2열을 갖는 2차원 배열

In [24]:
y = origin.reshape(-1, 2)
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

2. reshape(정수, -1)

2-1. 실습을 위한 원본 배열 생성

In [25]:
origin = np.arange(12)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

2-2. 열의 수에 관계 없이 1행을 갖는 2차원 배열로 재구성

In [26]:
x = origin.reshape(1, -1)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

2-3. 열의 수에 관계 없이 2행을 갖는 배열로 재구성

In [27]:
y = origin.reshape(2, -1)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

3. reshape(-1)

In [28]:
# 원본 배열
origin = np.array([
    [0, 1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10, 11]
])
print(origin)

# 1차 배열로 재배치
x = origin.reshape(-1)
x

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## 연습문제

### 데이터 포맷 정리

□ 당신은 데이터 분석팀의 “전처리 담당자”입니다.   
　팀에서 전달받은 데이터는 형태도 제각각이고, 타입도 일관되지 않아 분석이 어렵습니다.   

□ 아래 조건에 따라 NumPy를 이용해 데이터 타입과 구조를 정리하세요.   

- 0부터 11까지의 정수를 가지는 배열을 생성하시오.   
- 이 배열을 실수형(float) 으로 변환하시오.   
- 변환된 배열을 2행 6열 구조로 재배치하시오.   
- 이후, 열의 수에 관계없이 3행으로 자동 변환되도록 reshape() 함수를 이용하시오.   
- 마지막으로, 1차원 배열로 축소하여 결과를 출력하시오.

In [ ]:
import numpy as np

arr = np.arange(12)
myarray = arr.astype('float')
myarray_26 = myarray.reshape(2, 6)
myarray_3y = myarray.reshape(3, -1)
myarray_s = myarray.reshape(-1)

print("원본 배열:", arr)
print("실수형 변환:", myarray_float)
print("2행 6열 형태:\n", myarray_26)
print("자동 계산된 형태(3행 4열):\n", myarray_3y)
print("1차원 배열로 축소:\n", myarray_s)

원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]
실수형 변환: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
2행 6열 형태:
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
자동 계산된 형태(3행 4열):
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
1차원 배열로 축소:
 [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
