# [LAB-02] NumPy

## 5. 기술 통계량의 이해 (2)

### #01 준비작업

1. 라이브러리 참조

In [2]:
import numpy as np

2. 실습을 위한 샘플 데이터 준비

In [3]:
point = np.array([100, 91, 89, 86, 79, 78, 77, 74, 71, 69, 66, 65, 60, 58, 57, 55])
point

array([100,  91,  89,  86,  79,  78,  77,  74,  71,  69,  66,  65,  60,
        58,  57,  55])

### #02 NumPy의 histogram: 도수 분포도

1. 5개의 구간으로 나누기

In [4]:
hist, bins = np.histogram(point, 5)
print("구간별 데이터 수:", hist)
print("구간 경계:", bins)

구간별 데이터 수: [4 4 4 2 2]
구간 경계: [ 55.  64.  73.  82.  91. 100.]


2. 도수 분포표 구성

In [5]:
s = len(hist)
for i in range(0, s):
    if i + 1 < s:
        tpl = "%d이상 %d미만: %d개"
    else:
        tpl = "%d이상 %d미만: %d개"

    print(tpl % (bins[i], bins[i+1], hist[i]))

55이상 64미만: 4개
64이상 73미만: 4개
73이상 82미만: 4개
82이상 91미만: 2개
91이상 100미만: 2개


3. 데이터 구간을 직접 정의하기

In [6]:
hist, bins = np.histogram(point, [50, 60, 70, 80, 90, 100])
print("구간별 데이터 수:", hist)
print("구간 경계:", bins)

구간별 데이터 수: [3 4 5 2 2]
구간 경계: [ 50  60  70  80  90 100]


### #03 도수의 종류

1. 절대 도수

2. 상대 도수

In [7]:
relative_freq = hist / np.sum(hist)
relative_freq

array([0.1875, 0.25  , 0.3125, 0.125 , 0.125 ])

3. 누적 도수

In [8]:
cum_freq = []

previous = 0

for i in hist:
    previous += i
    cum_freq.append(previous)

cum_freq

[np.int64(3), np.int64(7), np.int64(12), np.int64(14), np.int64(16)]

## 연습문제

### 일일 판매량 데이터 분석

□ 당신은 한 온라인 상점의 한 달간 일일 판매량 데이터를 분석하는 임무를 맡았습니다.   
　주어진 데이터를 사용하여 판매량 분포를 파악하고,   
　아래 요구사항에 따라 분석 결과를 출력하는 Python 코드를 작성하세요.   

◎ 일일 판매량 데이터

18, 25, 33, 21, 28, 40, 15, 3, 9, 17, 22, 29, 38, 45, 11,   
6, 31, 24, 27, 35, 12, 19, 39, 42, 7, 2, 20, 34, 26, 30   

□ 요구사항

주어진 일일 판매량 데이터를 numpy 배열로 생성하세요.   
판매량 구간을 [0, 10, 20, 30, 40, 50]으로 직접 설정하여 도수분포를 분석하세요.   
2번의 도수 분포표를 활용하여 절대도수, 상대도수, 누적도수를 포함하는 도수분포표를 출력하세요.   
상대도수는 소수점 넷째 자리에서 반올림하여 셋째 자리까지 표시하세요.

In [9]:
data = np.array([18, 25, 33, 21, 28, 40, 15, 3, 9, 17, 22, 29, 38, 45, 11, 6, 31, 24, 27, 35, 12, 19, 39, 42, 7, 2, 20, 34, 26, 30])
data

array([18, 25, 33, 21, 28, 40, 15,  3,  9, 17, 22, 29, 38, 45, 11,  6, 31,
       24, 27, 35, 12, 19, 39, 42,  7,  2, 20, 34, 26, 30])

In [ ]:
hist, bins = np.histogram(data, [0, 10, 20, 30, 40, 50])
print("구간별 데이터 수:", hist)
print("구간 경계:", bins)

for i in range(0, len(hist)):
    if i + 1 < s:
        tpl = "%d이상 %d미만: %d개"
    else:
        tpl = "%d이상 %d미만: %d개"

    print(tpl % (bins[i], bins[i+1], hist[i]))

구간별 데이터 수: [5 6 9 7 3]
구간 경계: [ 0 10 20 30 40 50]
0이상 10미만: 5개
10이상 20미만: 6개
20이상 30미만: 9개
30이상 40미만: 7개
40이상 50미만: 3개


In [15]:
cum_freq = []

previous = 0

for i in hist:
    previous += i
    cum_freq.append(previous)

# 3. 도수분포표 출력
print("--- 일일 판매량 분석 ---")

for i in range(0, len(hist)):
    if i + 1 < s:
        tpl = "%d이상 %d미만: %d개"
    else:
        tpl = "%d이상 %d미만: %d개"

    # 출력 템플릿
    tpl = f"구간: {tpl} | 절대도수: {hist[i]} | 상대도수: {relative_freq[i]:.3f} | 누적도수: {cum_freq[i]}"
    print(tpl % (bins[i], bins[i+1], hist[i]))

--- 일일 판매량 분석 ---
구간: 0이상 10미만: 5개 | 절대도수: 5 | 상대도수: 0.188 | 누적도수: 5
구간: 10이상 20미만: 6개 | 절대도수: 6 | 상대도수: 0.250 | 누적도수: 11
구간: 20이상 30미만: 9개 | 절대도수: 9 | 상대도수: 0.312 | 누적도수: 20
구간: 30이상 40미만: 7개 | 절대도수: 7 | 상대도수: 0.125 | 누적도수: 27
구간: 40이상 50미만: 3개 | 절대도수: 3 | 상대도수: 0.125 | 누적도수: 30
